import Link from "next/link";
import { buildMetadata } from "../lib/seo";

export const metadata = buildMetadata({
  title: "Technology",
  description:
    "Morelle's adaptive charging technology: silicon-based anodes, charger-led intelligence, and validated durability for ultra-fast charging."
});

export default function TechnologyPage() {
  return (
    <div>
      {/* Hero */}
      <section className="section band-white">
        <div className="section-inner">
          <div className="max-w-3xl">
            <h1 className="mt-4 font-display text-4xl font-semibold leading-tight text-navy md:text-5xl">
              Fast charging. <span className="text-yellow">Without compromise.</span>
            </h1>
            <p className="mt-6 text-base leading-relaxed text-slate">
              We don't just charge batteries fast, we charge them intelligently. Our ML-driven 
              charging profiles optimize for speed while preserving long-term battery health. 
            </p>
            <div className="mt-8 flex flex-wrap gap-4">
              <Link href="/robotics#book-call" className="button-primary">
                Book a Call
              </Link>
            </div>
          </div>
        </div>
      </section>

      {/* Core Innovation */}
      <section className="bg-sand py-16 md:py-20">
        <div className="mx-auto max-w-7xl px-6 lg:px-8">
          <div className="text-center">
            <p className="text-xs uppercase tracking-[0.25em] text-slate">Core Innovation</p>
            <h2 className="mt-4 font-display text-3xl font-semibold text-navy md:text-4xl">
              Four pillars of intelligent charging.
            </h2>
          </div>
          <div className="mt-12 grid gap-8 md:grid-cols-2 lg:grid-cols-4">
            <div className="border border-navy/10 bg-white p-8">
              <p className="font-display text-xl font-semibold text-navy">Silicon Anodes</p>
              <p className="mt-4 text-sm leading-relaxed text-slate">
                Silicon-based anode chemistry enables higher energy density and faster 
                charge acceptance than traditional graphite.
              </p>
            </div>
            <div className="border border-navy/10 bg-white p-8">
              <p className="font-display text-xl font-semibold text-navy">ML-Optimized Profiles</p>
              <p className="mt-4 text-sm leading-relaxed text-slate">
                Custom charging profiles generated by Machine Learning models that learn from usage 
                patterns and real-time battery health.
              </p>
            </div>
            <div className="border border-navy/10 bg-white p-8">
              <p className="font-display text-xl font-semibold text-navy">SoH Optimization</p>
              <p className="mt-4 text-sm leading-relaxed text-slate">
                Every charge is optimized to maximize long-term State of Health, not 
                just speed, but also lasting performance.
              </p>
            </div>
            <div className="border border-navy/10 bg-white p-8">
              <p className="font-display text-xl font-semibold text-navy">System Integration</p>
              <p className="mt-4 text-sm leading-relaxed text-slate">
                Battery, BMS, and charger designed as one system. Tight integration 
                unlocks performance impossible with off-the-shelf parts.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Validation Stats */}
      <section className="bg-navy py-16">
        <div className="mx-auto max-w-7xl px-6 lg:px-8">
          <div className="grid gap-8 text-center md:grid-cols-4 md:gap-12">
            <div>
              <p className="font-display text-5xl font-semibold text-yellow md:text-6xl">1000+</p>
              <p className="mt-2 text-sm uppercase tracking-[0.25em] text-sand/70">Fast-charge cycles</p>
            </div>
            <div>
              <p className="font-display text-5xl font-semibold text-yellow md:text-6xl">5C</p>
              <p className="mt-2 text-sm uppercase tracking-[0.25em] text-sand/70">Charge rate tested</p>
            </div>
            <div>
              <p className="font-display text-5xl font-semibold text-yellow md:text-6xl">15</p>
              <p className="mt-2 text-sm uppercase tracking-[0.25em] text-sand/70">Minutes to full</p>
            </div>
            <div>
              <p className="font-display text-5xl font-semibold text-yellow md:text-6xl">UL</p>
              <p className="mt-2 text-sm uppercase tracking-[0.25em] text-sand/70">Certified systems</p>
            </div>
          </div>
          <p className="mt-8 text-center text-xs text-sand/60">
            Validated in internal testing. Performance may vary by application.
          </p>
        </div>
      </section>

      {/* Beyond CC-CV */}
      <section className="bg-white py-20 md:py-28">
        <div className="mx-auto max-w-7xl px-6 lg:px-8">
          <div className="max-w-3xl">
            <p className="text-xs uppercase tracking-[0.25em] text-navy">Beyond Traditional Charging</p>
            <h2 className="mt-4 font-display text-3xl font-semibold text-navy md:text-4xl">
              Why CC-CV isn't enough.
            </h2>
            <p className="mt-6 text-base leading-relaxed text-slate">
              Traditional Constant Current - Constant Voltage (CC-CV) charging uses a 
              one-size-fits-all approach.
            </p>
            <p className="mt-0 text-base leading-relaxed text-slate">
              It doesn't account for battery age, temperature, 
              usage patterns, or cell-level variations.
            </p>
          </div>
          <div className="mt-12 grid gap-8 lg:grid-cols-2">
            <div className="border border-red-200 bg-red-50 p-8">
              <p className="font-display text-xl font-semibold text-red-900">The CC-CV Problem</p>
              <ul className="mt-4 space-y-3 text-sm text-red-800">
                <li className="flex items-start gap-2">
                  <span>✗</span>
                  Fixed current regardless of battery state
                </li>
                <li className="flex items-start gap-2">
                  <span>✗</span>
                  Same profile for new and aged cells
                </li>
                <li className="flex items-start gap-2">
                  <span>✗</span>
                  No adaptation to temperature conditions
                </li>
                <li className="flex items-start gap-2">
                  <span>✗</span>
                  Conservative limits leave speed on the table
                </li>
                <li className="flex items-start gap-2">
                  <span>✗</span>
                  Accelerates degradation at high C-rates
                </li>
              </ul>
            </div>
            <div className="border border-navy bg-navy p-8">
              <p className="font-display text-xl font-semibold text-yellow">Morelle Adaptive Charging</p>
              <ul className="mt-4 space-y-3 text-sm text-sand/90">
                <li className="flex items-start gap-2">
                  <span className="text-yellow">✓</span>
                  Dynamic current based on real-time SoH
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-yellow">✓</span>
                  ML-generated profiles for each unique packs
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-yellow">✓</span>
                  Thermal-aware current modulation
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-yellow">✓</span>
                  Pushes safe limits for maximum speed
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-yellow">✓</span>
                  Optimizes for long-term cycle life
                </li>
              </ul>
            </div>
          </div>
        </div>
      </section>

      {/* Charging Levels */}
      <section className="bg-sand py-16 md:py-20">
        <div className="mx-auto max-w-7xl px-6 lg:px-8">
          <div className="text-center">
            <p className="text-xs uppercase tracking-[0.25em] text-slate">Charging Levels</p>
            <h2 className="mt-4 font-display text-3xl font-semibold text-navy md:text-4xl">
              Multiple tiers for different use cases.
            </h2>
            <p className="mx-auto mt-4 max-w-2xl text-base text-slate">
              From standard charging to ultra-fast proprietary systems, Morelle supports
              the full micromobility charging envelope.
            </p>
          </div>
          <div className="mt-12 grid gap-6 md:grid-cols-3">
            <div className="border border-navy/10 bg-white p-8">
              <p className="text-xs uppercase tracking-[0.25em] text-slate">Level M1</p>
              <p className="mt-2 font-display text-3xl font-semibold text-navy">100–300W</p>
              <p className="mt-4 text-sm text-slate">
                Standard charging using conventional infrastructure. Typical full charge in 2–4 hours, depending on pack size.
              </p>
            </div>
            <div className="border border-navy bg-white p-8">
              <p className="text-xs uppercase tracking-[0.25em] text-slate">Level M2</p>
              <p className="mt-2 font-display text-3xl font-semibold text-navy">1000–1200W</p>
              <p className="mt-4 text-sm text-slate">
                Morelle-supported fast charging. Typical full charge in 30–45 minutes with compatible chargers and cells.
              </p>
            </div>
            <div className="border border-yellow bg-navy p-8">
              <p className="text-xs uppercase tracking-[0.25em] text-yellow/70">Level M3</p>
              <p className="mt-2 font-display text-3xl font-semibold text-yellow">1500W+</p>
              <p className="mt-4 text-sm text-yellow/80">
                Morelle proprietary ultra-fast charging. Operational full charge in under 15 minutes on supported packs. Maximum performance.
              </p>
            </div>
          </div>
          <p className="mt-8 text-center text-xs text-slate/70">
            Charging levels reflect the micromobility envelope and may vary by use case.
          </p>
        </div>
      </section>

      {/* ML-Driven Charging */}
      <section className="bg-white py-20 md:py-28">
        <div className="mx-auto max-w-7xl px-6 lg:px-8">
          <div className="grid items-center gap-12 lg:grid-cols-2 lg:gap-16">
            <div>
              <p className="text-xs uppercase tracking-[0.25em] text-slate">Machine Learning</p>
              <h2 className="mt-4 font-display text-3xl font-semibold text-navy md:text-4xl">
                Every charge makes us smarter.
              </h2>
              <p className="mt-6 text-base leading-relaxed text-slate">
                Our charging profile continuously adapts based on how each battery is used, charged, and aged. Over time, it learns the conditions under which a battery can safely charge faster and when it should slow down.
              </p>
              <ul className="mt-6 space-y-4 text-sm text-slate">
                <li className="flex items-start gap-3">
                  <span className="text-yellow">→</span>
                  <div>
                    <span className="font-semibold text-navy">Learns from usage</span>
                    <p className="mt-1">Charging behavior adapts based on usage, battery health, and operating conditions.</p>
                  </div>
                </li>
                <li className="flex items-start gap-3">
                  <span className="text-yellow">→</span>
                  <div>
                    <span className="font-semibold text-navy">Adjusts in real time</span>
                    <p className="mt-1">Charge rate and limits are continuously tuned based on real time conditions.</p>
                  </div>
                </li>
                <li className="flex items-start gap-3">
                  <span className="text-yellow">→</span>
                  <div>
                    <span className="font-semibold text-navy">Reduces long-term stress</span>
                    <p className="mt-1">Charging behavior is modified over time to avoid conditions associated with accelerated wear.</p>
                  </div>
                </li>
                <li className="flex items-start gap-3">
                  <span className="text-yellow">→</span>
                  <div>
                    <span className="font-semibold text-navy">Improves across deployments</span>
                    <p className="mt-1">Insights from deployed systems inform ongoing improvements to charging behavior.</p>
                  </div>
                </li>
              </ul>
            </div>
            <div className="bg-sand border border-navy/10 p-8">
              <p className="text-xs uppercase tracking-[0.25em] text-slate">How It Works</p>
              <h3 className="mt-4 font-display text-xl font-semibold text-navy">Adaptive Charging Cycle</h3>
              <div className="mt-6 space-y-6">
                <div className="flex items-center gap-4">
                  <div className="flex h-8 w-8 shrink-0 items-center justify-center bg-navy text-sm font-bold text-white">1</div>
                  <div>
                    <p className="font-semibold text-navy">Sense</p>
                    <p className="text-sm text-slate">Monitor key electrical and thermal signals during charging.</p>
                  </div>
                </div>
                <div className="flex items-center gap-4">
                  <div className="flex h-8 w-8 shrink-0 items-center justify-center bg-navy text-sm font-bold text-white">2</div>
                  <div>
                    <p className="font-semibold text-navy">Evaluate</p>
                    <p className="text-sm text-slate">Determine safe and effective charging limits for the current conditions.</p>
                  </div>
                </div>
                <div className="flex items-center gap-4">
                  <div className="flex h-8 w-8 shrink-0 items-center justify-center bg-navy text-sm font-bold text-white">3</div>
                  <div>
                    <p className="font-semibold text-navy">Apply</p>
                    <p className="text-sm text-slate">Deliver a custom charge profile for the session.</p>
                  </div>
                </div>
                <div className="flex items-center gap-4">
                  <div className="flex h-8 w-8 shrink-0 items-center justify-center bg-navy text-sm font-bold text-white">4</div>
                  <div>
                    <p className="font-semibold text-navy">Refine</p>
                    <p className="text-sm text-slate">Continuously adjust as conditions change.</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Team */}
      <section className="bg-navy py-16 md:py-20">
        <div className="mx-auto max-w-7xl px-6 lg:px-8">
          <div className="text-center">
            <h2 className="mt-4 font-display text-3xl font-semibold text-sand md:text-4xl">
              The Team.
            </h2>
          </div>
          <div className="mt-12 grid gap-12 md:grid-cols-3">
            <div className="text-center">
              <img
                src="/team/MichaelSinkula.jpg"
                alt="Michael Sinkula"
                className="border border-yellow/50 mx-auto mb-4 h-48 w-48 object-cover"
              />
              <p className="font-display text-xl font-semibold text-yellow">Michael Sinkula</p>
              <p className="mt-1 text-sm text-sand/70">Co-founder & CEO</p>
              <a
                href="https://www.linkedin.com/in/michael-sinkula-4911181/"
                target="_blank"
                rel="noopener noreferrer"
                className="mt-3 inline-flex items-center gap-2 text-yellow transition-opacity hover:opacity-80"
              >
                <svg className="h-5 w-5" fill="currentColor" viewBox="0 0 24 24">
                  <path d="M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433c-1.144 0-2.063-.926-2.063-2.065 0-1.138.92-2.063 2.063-2.063 1.14 0 2.064.925 2.064 2.063 0 1.139-.925 2.065-2.064 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.225 0z" />
                </svg>
              </a>
            </div>
            <div className="text-center">
              <img
                src="/team/KevinHays.jpg"
                alt="Dr. Kevin Hays"
                className="border border-yellow/50 mx-auto mb-4 h-48 w-48 object-cover"
              />
              <p className="font-display text-xl font-semibold text-yellow">Dr. Kevin Hays</p>
              <p className="mt-1 text-sm text-sand/70">Co-founder & CTO</p>
              <a
                href="https://www.linkedin.com/in/kevin-hays-243202153/"
                target="_blank"
                rel="noopener noreferrer"
                className="mt-3 inline-flex items-center gap-2 text-yellow transition-opacity hover:opacity-80"
              >
                <svg className="h-5 w-5" fill="currentColor" viewBox="0 0 24 24">
                  <path d="M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433c-1.144 0-2.063-.926-2.063-2.065 0-1.138.92-2.063 2.063-2.063 1.14 0 2.064.925 2.064 2.063 0 1.139-.925 2.065-2.064 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.225 0z" />
                </svg>
              </a>
            </div>
            <div className="text-center">
              <img
                src="/team/GaryFisher.jpg"
                alt="Gary Fisher"
                className="border border-yellow/50 mx-auto mb-4 h-48 w-48 object-cover"
              />
              <p className="font-display text-xl font-semibold text-yellow">Gary Fisher</p>
              <p className="mt-1 text-sm text-sand/70">Head Developer, MTB pioneer</p>
              <a
                href="https://www.linkedin.com/in/gary-fisher-4281545/"
                target="_blank"
                rel="noopener noreferrer"
                className="mt-3 inline-flex items-center gap-2 text-yellow transition-opacity hover:opacity-80"
              >
                <svg className="h-5 w-5" fill="currentColor" viewBox="0 0 24 24">
                  <path d="M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433c-1.144 0-2.063-.926-2.063-2.065 0-1.138.92-2.063 2.063-2.063 1.14 0 2.064.925 2.064 2.063 0 1.139-.925 2.065-2.064 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.225 0z" />
                </svg>
              </a>
            </div>
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="bg-white py-16 md:py-20">
        <div className="mx-auto max-w-4xl px-6 text-center lg:px-8">
          <h2 className="font-display text-3xl font-semibold text-navy md:text-4xl">
            Ready to see the technology in action?
          </h2>
          <p className="mx-auto mt-4 max-w-xl text-base text-slate">
            Whether you're building robots or looking for the fastest-charging e-bike,
            we'd love to show you what Morelle can do.
          </p>
          <div className="mt-8 flex flex-wrap justify-center gap-4">
            <Link href="/reserve" className="button-primary">
              Reserve E-Bike
            </Link>
            <Link href="/robotics#book-call" className="button-outline">
              Book a Call
            </Link>
          </div>
        </div>
      </section>
    </div>
  );
}
